name: Deploy site to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "public/**"
      - ".github/workflows/main.yml"
      - ".github/workflows/static.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/static.yml
